$NetBSD: patch-Cargo.toml,v 1.24 2023/03/28 20:28:51 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2.

--- Cargo.toml.orig	2023-03-25 06:02:33.000000000 +0000
+++ Cargo.toml
@@ -70,7 +70,7 @@ features = ['serde']
 
 [dependencies.mlua]
 version = "0.8.8"
-features = ['luajit', 'vendored', 'serialize', 'send']
+features = ['luajit', 'serialize', 'send']
 
 [dependencies.tui-input]
 version = "0.7.0"
